global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'turboauth'
    static_configs:
      - targets: ['api:2112']
        labels:
          service: 'turboauth-api'
